version: "3.9"

services: 
  job_db:
    image: redis/redis-stack-server:latest
    logging:
      driver: none
    ports:
      - "6379:6379"

  client_db_0:
    image: redis/redis-stack-server:latest
    logging:
      driver: none
    ports:
      - "6380:6380"