version: "3.9"

services:
  scheduler:
    build: 
      context: .
      dockerfile: ./propius/scheduler/Dockerfile
    volumes:
      - ./propius/scheduler:/propius/scheduler
      - ./propius/global_config.yml:/propius/global_config.yml
    depends_on:
      - job_db
      - client_db_0
    stop_signal: SIGINT

  job_manager:
    build:
      context: .
      dockerfile: ./propius/job_manager/Dockerfile
    ports:
      - "50001:50001"
    volumes:
      - ./propius/job_manager:/propius/job_manager
      - ./propius/global_config.yml:/propius/global_config.yml
    depends_on:
      - scheduler
    stop_signal: SIGINT

  client_manager_0:
    build:
      context: .
      dockerfile: ./propius/client_manager/Dockerfile
    volumes:
      - ./propius/client_manager:/propius/client_manager
      - ./propius/global_config.yml:/propius/global_config.yml
    depends_on:
      - job_db
      - client_db_0
    stop_signal: SIGINT
    command: ["0"]
  
  load_balancer:
    build:
      context: .
      dockerfile: ./propius/load_balancer/Dockerfile
    ports:
      - "50002:50002"
    volumes:
      - ./propius/load_balancer:/propius/load_balancer
      - ./propius/global_config.yml:/propius/global_config.yml
    depends_on:
      - client_manager_0
    stop_signal: SIGINT

  job_db:
    image: redis/redis-stack-server:latest
    volumes:
        - job_redis_data:/data
    logging:
      driver: none  

  client_db_0:
    image: redis/redis-stack-server:latest
    volumes:
        - client_0_data:/data
    logging:
      driver: none

volumes:
  job_redis_data:
  client_0_data:
  client_1_data: