version: '3.9'

services:
  scheduler:
    build:
      context: .
      dockerfile: ./propius/scheduler/Dockerfile
    volumes:
    - ./propius:/propius
    depends_on:
    - client_db_0
    - client_db_1
    - job_db
    stop_signal: SIGINT
    environment:
    - TZ=America/Detroit
  job_manager:
    build:
      context: .
      dockerfile: ./propius/job_manager/Dockerfile
    volumes:
    - ./propius:/propius
    depends_on:
    - scheduler
    - job_db
    stop_signal: SIGINT
    environment:
    - TZ=America/Detroit
  load_balancer:
    build:
      context: .
      dockerfile: ./propius/load_balancer/Dockerfile
    volumes:
    - ./propius:/propius
    depends_on:
    - client_manager_0
    - client_manager_1
    stop_signal: SIGINT
    environment:
    - TZ=America/Detroit
  job_db:
    build:
      context: .
      dockerfile: ./propius/database/Dockerfile
    command: ['6379']
    environment:
    - TZ=America/Detroit
  client_manager_0:
    build:
      context: .
      dockerfile: ./propius/client_manager/Dockerfile
    volumes:
    - ./propius:/propius
    depends_on:
    - job_db
    - client_db_0
    - scheduler
    command:
    - '0'
    environment:
    - TZ=America/Detroit
    stop_signal: SIGINT
  client_db_0:
    build:
      context: .
      dockerfile: ./propius/database/Dockerfile
    command:
    - '6380'
    environment:
    - TZ=America/Detroit
  client_manager_1:
    build:
      context: .
      dockerfile: ./propius/client_manager/Dockerfile
    volumes:
    - ./propius:/propius
    depends_on:
    - job_db
    - client_db_1
    - scheduler
    command:
    - '1'
    environment:
    - TZ=America/Detroit
    stop_signal: SIGINT
  client_db_1:
    build:
      context: .
      dockerfile: ./propius/database/Dockerfile
    command:
    - '6381'
    environment:
    - TZ=America/Detroit
  jobs_0:
    build:
      context: .
      dockerfile: ./evaluation/job/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./propius:/propius
    stop_signal: SIGINT
    depends_on:
    - job_manager
    command:
    - '0'
    - '1'
    - '0'
    environment:
    - TZ=America/Detroit
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.75'
          memory: 800M
  jobs_1:
    build:
      context: .
      dockerfile: ./evaluation/job/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./propius:/propius
    stop_signal: SIGINT
    depends_on:
    - job_manager
    command:
    - '1'
    - '2'
    - '1'
    environment:
    - TZ=America/Detroit
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.75'
          memory: 800M
  jobs_2:
    build:
      context: .
      dockerfile: ./evaluation/job/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./propius:/propius
    stop_signal: SIGINT
    depends_on:
    - job_manager
    command:
    - '2'
    - '3'
    - '2'
    environment:
    - TZ=America/Detroit
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.75'
          memory: 800M
  jobs_3:
    build:
      context: .
      dockerfile: ./evaluation/job/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./propius:/propius
    stop_signal: SIGINT
    depends_on:
    - job_manager
    command:
    - '3'
    - '4'
    - '3'
    environment:
    - TZ=America/Detroit
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.75'
          memory: 800M
  jobs_4:
    build:
      context: .
      dockerfile: ./evaluation/job/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./propius:/propius
    stop_signal: SIGINT
    depends_on:
    - job_manager
    command:
    - '4'
    - '5'
    - '4'
    environment:
    - TZ=America/Detroit
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.75'
          memory: 800M
  jobs_5:
    build:
      context: .
      dockerfile: ./evaluation/job/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./propius:/propius
    stop_signal: SIGINT
    depends_on:
    - job_manager
    command:
    - '5'
    - '6'
    - '5'
    environment:
    - TZ=America/Detroit
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.75'
          memory: 800M
  jobs_6:
    build:
      context: .
      dockerfile: ./evaluation/job/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./propius:/propius
    stop_signal: SIGINT
    depends_on:
    - job_manager
    command:
    - '6'
    - '7'
    - '6'
    environment:
    - TZ=America/Detroit
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.75'
          memory: 800M
  jobs_7:
    build:
      context: .
      dockerfile: ./evaluation/job/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./propius:/propius
    stop_signal: SIGINT
    depends_on:
    - job_manager
    command:
    - '7'
    - '8'
    - '7'
    environment:
    - TZ=America/Detroit
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.75'
          memory: 800M
  jobs_8:
    build:
      context: .
      dockerfile: ./evaluation/job/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./propius:/propius
    stop_signal: SIGINT
    depends_on:
    - job_manager
    command:
    - '8'
    - '9'
    - '8'
    environment:
    - TZ=America/Detroit
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.75'
          memory: 800M
  jobs_9:
    build:
      context: .
      dockerfile: ./evaluation/job/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./propius:/propius
    stop_signal: SIGINT
    depends_on:
    - job_manager
    command:
    - '9'
    - '10'
    - '9'
    environment:
    - TZ=America/Detroit
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.75'
          memory: 800M
  clients_0:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation/client:/evaluation/client
    - ./evaluation/evaluation_config.yml:/evaluation/evaluation_config.yml
    - ./datasets/device_info:/datasets/device_info
    - ./evaluation/monitor:/evaluation/monitor
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '0'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.75'
          memory: 500M
  clients_1:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation/client:/evaluation/client
    - ./evaluation/evaluation_config.yml:/evaluation/evaluation_config.yml
    - ./datasets/device_info:/datasets/device_info
    - ./evaluation/monitor:/evaluation/monitor
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '1'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.75'
          memory: 500M
  clients_2:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation/client:/evaluation/client
    - ./evaluation/evaluation_config.yml:/evaluation/evaluation_config.yml
    - ./datasets/device_info:/datasets/device_info
    - ./evaluation/monitor:/evaluation/monitor
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '2'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.75'
          memory: 500M
  clients_3:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation/client:/evaluation/client
    - ./evaluation/evaluation_config.yml:/evaluation/evaluation_config.yml
    - ./datasets/device_info:/datasets/device_info
    - ./evaluation/monitor:/evaluation/monitor
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '3'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.75'
          memory: 500M
  clients_4:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation/client:/evaluation/client
    - ./evaluation/evaluation_config.yml:/evaluation/evaluation_config.yml
    - ./datasets/device_info:/datasets/device_info
    - ./evaluation/monitor:/evaluation/monitor
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '4'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.75'
          memory: 500M
  clients_5:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation/client:/evaluation/client
    - ./evaluation/evaluation_config.yml:/evaluation/evaluation_config.yml
    - ./datasets/device_info:/datasets/device_info
    - ./evaluation/monitor:/evaluation/monitor
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '5'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.75'
          memory: 500M
  clients_6:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation/client:/evaluation/client
    - ./evaluation/evaluation_config.yml:/evaluation/evaluation_config.yml
    - ./datasets/device_info:/datasets/device_info
    - ./evaluation/monitor:/evaluation/monitor
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '6'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.75'
          memory: 500M
  clients_7:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation/client:/evaluation/client
    - ./evaluation/evaluation_config.yml:/evaluation/evaluation_config.yml
    - ./datasets/device_info:/datasets/device_info
    - ./evaluation/monitor:/evaluation/monitor
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '7'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.75'
          memory: 500M
