version: "3.9"

services:
  scheduler:
    build: 
      context: .
      dockerfile: ./propius/scheduler/Dockerfile
    volumes:
      - ./propius/scheduler:/propius/scheduler
      - ./propius/global_config.yml:/propius/global_config.yml
      - ./propius/monitor:/propius/monitor
    depends_on:
      - job_db
      - client_db_0
      - client_db_1
    stop_signal: SIGINT

  job_manager:
    build:
      context: .
      dockerfile: ./propius/job_manager/Dockerfile
    volumes:
      - ./propius/job_manager:/propius/job_manager
      - ./propius/global_config.yml:/propius/global_config.yml
      - ./propius/monitor:/propius/monitor
    depends_on:
      - scheduler
    stop_signal: SIGINT

  client_manager_0:
    build:
      context: .
      dockerfile: ./propius/client_manager/Dockerfile
    volumes:
      - ./propius/client_manager:/propius/client_manager
      - ./propius/global_config.yml:/propius/global_config.yml
      - ./propius/monitor:/propius/monitor
    depends_on:
      - job_db
      - client_db_0
    stop_signal: SIGINT
    command: ["0"]

  client_manager_1:
    build:
      context: .
      dockerfile: ./propius/client_manager/Dockerfile
    volumes:
      - ./propius/client_manager:/propius/client_manager
      - ./propius/global_config.yml:/propius/global_config.yml
      - ./propius/monitor:/propius/monitor
    depends_on:
      - job_db
      - client_db_1
    stop_signal: SIGINT
    command: ["1"]
  
  load_balancer:
    build:
      context: .
      dockerfile: ./propius/load_balancer/Dockerfile
    volumes:
      - ./propius/load_balancer:/propius/load_balancer
      - ./propius/global_config.yml:/propius/global_config.yml
      - ./propius/monitor:/propius/monitor
    depends_on:
      - client_manager_0
      - client_manager_1
    stop_signal: SIGINT

  job_db:
    build:
      context: .
      dockerfile: ./propius/database/Dockerfile
    command: ["6379"]

  client_db_0:
    build:
      context: .
      dockerfile: ./propius/database/Dockerfile
    command: ["6380"]

  client_db_1:
    build:
      context: .
      dockerfile: ./propius/database/Dockerfile
    command: ["6381"]
    
  worker_0:
    build:
      context: .
      dockerfile: ./evaluation/executor/Dockerfile_worker_gpu
      args:
        WORKER_IMAGE: nvidia/cuda:11.6.2-devel-ubuntu20.04
    volumes:
      - ./evaluation/executor:/evaluation/executor
      - ./evaluation/evaluation_config.yml:/evaluation/evaluation_config.yml
      - ./datasets:/datasets
      - ./evaluation/monitor:/evaluation/monitor
    stop_signal: SIGINT
    command: ["0"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 4
              capabilities: [gpu]

  worker_1:
    build:
      context: .
      dockerfile: ./evaluation/executor/Dockerfile_worker_gpu
      args:
        WORKER_IMAGE: nvidia/cuda:11.6.2-devel-ubuntu20.04
    volumes:
      - ./evaluation/executor:/evaluation/executor
      - ./evaluation/evaluation_config.yml:/evaluation/evaluation_config.yml
      - ./datasets:/datasets
      - ./evaluation/monitor:/evaluation/monitor
    stop_signal: SIGINT
    command: ["1"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 4
              capabilities: [gpu]
  
  worker_2:
    build:
      context: .
      dockerfile: ./evaluation/executor/Dockerfile_worker_gpu
      args:
        WORKER_IMAGE: nvidia/cuda:11.6.2-devel-ubuntu20.04
    volumes:
      - ./evaluation/executor:/evaluation/executor
      - ./evaluation/evaluation_config.yml:/evaluation/evaluation_config.yml
      - ./datasets:/datasets
      - ./evaluation/monitor:/evaluation/monitor
    stop_signal: SIGINT
    command: ["2"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 4
              capabilities: [gpu]
  
  executor:
    build: 
      context: .
      dockerfile: ./evaluation/executor/Dockerfile_executor
    volumes:
      - ./evaluation/executor:/evaluation/executor
      - ./evaluation/evaluation_config.yml:/evaluation/evaluation_config.yml
      - ./evaluation/monitor:/evaluation/monitor
    stop_signal: SIGINT
    depends_on:
      - worker_0
      - worker_1
      - worker_2
  
  clients:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
      - ./evaluation/client:/evaluation/client
      - ./evaluation/evaluation_config.yml:/evaluation/evaluation_config.yml
      - ./datasets/device_info:/datasets/device_info
      - ./evaluation/monitor:/evaluation/monitor
    stop_signal: SIGINT
    depends_on:
      - load_balancer
      

  jobs:
    build:
      context: .
      dockerfile: ./evaluation/job/Dockerfile
    volumes:
      - ./evaluation/job:/evaluation/job
      - ./evaluation/evaluation_config.yml:/evaluation/evaluation_config.yml
      - ./evaluation/monitor:/evaluation/monitor
    stop_signal: SIGINT
    depends_on:
      - executor
      - clients
      - job_manager