version: "3.9"

services:
  executor:
    build: 
      context: .
      dockerfile: ./evaluation/single_executor/Dockerfile
    volumes:
      - ./evaluation/single_executor:/evaluation/single_executor
      - ./evaluation/evaluation_config.yml:/evaluation/evaluation_config.yml
    ports:
      - "49999:49999"
    stop_signal: SIGINT