version: "3.9"

services:
  scheduler:
    build: 
      context: .
      dockerfile: ./propius/scheduler/Dockerfile
    volumes:
      - ./propius/scheduler:/propius/scheduler

  job_manager:
    build:
      context: .
      dockerfile: ./propius/job_manager/Dockerfile
    volumes:
      - ./propius/job_manager:/propius/job_manager
  
  job_db:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    volumes:
        - job_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping"]
      interval: 2s
      timeout: 1m30s
      retries: 5
      start_period: 5s
  client_db_0:
    image: redis/redis-stack-server:latest
    ports:
      - "6380:6379"
    volumes:
        - client_0_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6380", "ping"]
      interval: 2s
      timeout: 1m30s
      retries: 5
      start_period: 5s

volumes:

  job_redis_data:
  client_0_data:
  client_1_data: