version: '3.9'

services:
  scheduler:
    build:
      context: .
      dockerfile: ./propius/scheduler/Dockerfile
    volumes:
    - ./propius:/propius
    depends_on:
    - client_db_0
    - client_db_1
    - job_db
    stop_signal: SIGINT
    environment:
    - TZ=America/Detroit
  job_manager:
    build:
      context: .
      dockerfile: ./propius/job_manager/Dockerfile
    volumes:
    - ./propius:/propius
    depends_on:
    - scheduler
    stop_signal: SIGINT
    environment:
    - TZ=America/Detroit
  load_balancer:
    build:
      context: .
      dockerfile: ./propius/load_balancer/Dockerfile
    volumes:
    - ./propius:/propius
    depends_on:
    - client_manager_0
    - client_manager_1
    stop_signal: SIGINT
    environment:
    - TZ=America/Detroit
  job_db:
    build:
      context: .
      dockerfile: ./propius/database/Dockerfile
    command: ['6379']
    environment:
    - TZ=America/Detroit
  executor:
    build:
      context: .
      dockerfile: ./evaluation/executor/Dockerfile_executor
    volumes:
    - ./evaluation:/evaluation
    stop_signal: SIGINT
    depends_on:
    - worker_0
    - worker_1
    - worker_2
    - worker_3
    - worker_4
    - worker_5
    - worker_6
    - worker_7
    - worker_8
    - worker_9
    - worker_10
    - worker_11
    - worker_12
    - worker_13
    - worker_14
    - worker_15
    environment:
    - TZ=America/Detroit

  client_manager_0:
    build:
      context: .
      dockerfile: ./propius/client_manager/Dockerfile
    volumes:
    - ./propius:/propius
    depends_on:
    - job_db
    - client_db_0
    - scheduler
    command:
    - '0'
    environment:
    - TZ=America/Detroit
    stop_signal: SIGINT
  client_db_0:
    build:
      context: .
      dockerfile: ./propius/database/Dockerfile
    command:
    - '6380'
    environment:
    - TZ=America/Detroit
  client_manager_1:
    build:
      context: .
      dockerfile: ./propius/client_manager/Dockerfile
    volumes:
    - ./propius:/propius
    depends_on:
    - job_db
    - client_db_1
    - scheduler
    command:
    - '1'
    environment:
    - TZ=America/Detroit
    stop_signal: SIGINT
  client_db_1:
    build:
      context: .
      dockerfile: ./propius/database/Dockerfile
    command:
    - '6381'
    environment:
    - TZ=America/Detroit
  jobs_0:
    build:
      context: .
      dockerfile: ./evaluation/job/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./propius:/propius
    stop_signal: SIGINT
    depends_on:
    - job_manager
    command:
    - '0'
    - '2'
    - '0'
    environment:
    - TZ=America/Detroit
  jobs_1:
    build:
      context: .
      dockerfile: ./evaluation/job/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./propius:/propius
    stop_signal: SIGINT
    depends_on:
    - job_manager
    command:
    - '2'
    - '4'
    - '1'
    environment:
    - TZ=America/Detroit
  jobs_2:
    build:
      context: .
      dockerfile: ./evaluation/job/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./propius:/propius
    stop_signal: SIGINT
    depends_on:
    - job_manager
    command:
    - '4'
    - '6'
    - '2'
    environment:
    - TZ=America/Detroit
  jobs_3:
    build:
      context: .
      dockerfile: ./evaluation/job/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./propius:/propius
    stop_signal: SIGINT
    depends_on:
    - job_manager
    command:
    - '6'
    - '8'
    - '3'
    environment:
    - TZ=America/Detroit
  jobs_4:
    build:
      context: .
      dockerfile: ./evaluation/job/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./propius:/propius
    stop_signal: SIGINT
    depends_on:
    - job_manager
    command:
    - '8'
    - '10'
    - '4'
    environment:
    - TZ=America/Detroit
  clients_0:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./datasets/device_info:/datasets/device_info
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '0'
  clients_1:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./datasets/device_info:/datasets/device_info
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '1'
  clients_2:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./datasets/device_info:/datasets/device_info
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '2'
  clients_3:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./datasets/device_info:/datasets/device_info
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '3'
  clients_4:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./datasets/device_info:/datasets/device_info
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '4'
  clients_5:
    build:
      context: .
      dockerfile: ./evaluation/client/Dockerfile
    volumes:
    - ./evaluation:/evaluation
    - ./datasets/device_info:/datasets/device_info
    stop_signal: SIGINT
    depends_on:
    - load_balancer
    environment:
    - TZ=America/Detroit
    command:
    - '1000'
    - '5'
  worker_0:
    build:
      context: .
      dockerfile: ./evaluation/executor/Dockerfile_worker_gpu
      args:
        WORKER_IMAGE: nvidia/cuda:11.6.2-devel-ubuntu20.04
    volumes:
    - ./evaluation:/evaluation
    - ./datasets:/datasets
    stop_signal: SIGINT
    command:
    - '0'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 4
            capabilities:
            - gpu
    environment:
    - TZ=America/Detroit
  worker_1:
    build:
      context: .
      dockerfile: ./evaluation/executor/Dockerfile_worker_gpu
      args:
        WORKER_IMAGE: nvidia/cuda:11.6.2-devel-ubuntu20.04
    volumes:
    - ./evaluation:/evaluation
    - ./datasets:/datasets
    stop_signal: SIGINT
    command:
    - '1'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 4
            capabilities:
            - gpu
    environment:
    - TZ=America/Detroit
  worker_2:
    build:
      context: .
      dockerfile: ./evaluation/executor/Dockerfile_worker_gpu
      args:
        WORKER_IMAGE: nvidia/cuda:11.6.2-devel-ubuntu20.04
    volumes:
    - ./evaluation:/evaluation
    - ./datasets:/datasets
    stop_signal: SIGINT
    command:
    - '2'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 4
            capabilities:
            - gpu
    environment:
    - TZ=America/Detroit
  worker_3:
    build:
      context: .
      dockerfile: ./evaluation/executor/Dockerfile_worker_gpu
      args:
        WORKER_IMAGE: nvidia/cuda:11.6.2-devel-ubuntu20.04
    volumes:
    - ./evaluation:/evaluation
    - ./datasets:/datasets
    stop_signal: SIGINT
    command:
    - '3'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 4
            capabilities:
            - gpu
    environment:
    - TZ=America/Detroit
  worker_4:
    build:
      context: .
      dockerfile: ./evaluation/executor/Dockerfile_worker_gpu
      args:
        WORKER_IMAGE: nvidia/cuda:11.6.2-devel-ubuntu20.04
    volumes:
    - ./evaluation:/evaluation
    - ./datasets:/datasets
    stop_signal: SIGINT
    command:
    - '4'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 4
            capabilities:
            - gpu
    environment:
    - TZ=America/Detroit
  worker_5:
    build:
      context: .
      dockerfile: ./evaluation/executor/Dockerfile_worker_gpu
      args:
        WORKER_IMAGE: nvidia/cuda:11.6.2-devel-ubuntu20.04
    volumes:
    - ./evaluation:/evaluation
    - ./datasets:/datasets
    stop_signal: SIGINT
    command:
    - '5'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 4
            capabilities:
            - gpu
    environment:
    - TZ=America/Detroit
  worker_6:
    build:
      context: .
      dockerfile: ./evaluation/executor/Dockerfile_worker_gpu
      args:
        WORKER_IMAGE: nvidia/cuda:11.6.2-devel-ubuntu20.04
    volumes:
    - ./evaluation:/evaluation
    - ./datasets:/datasets
    stop_signal: SIGINT
    command:
    - '6'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 4
            capabilities:
            - gpu
    environment:
    - TZ=America/Detroit
  worker_7:
    build:
      context: .
      dockerfile: ./evaluation/executor/Dockerfile_worker_gpu
      args:
        WORKER_IMAGE: nvidia/cuda:11.6.2-devel-ubuntu20.04
    volumes:
    - ./evaluation:/evaluation
    - ./datasets:/datasets
    stop_signal: SIGINT
    command:
    - '7'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 4
            capabilities:
            - gpu
    environment:
    - TZ=America/Detroit
  worker_8:
    build:
      context: .
      dockerfile: ./evaluation/executor/Dockerfile_worker_gpu
      args:
        WORKER_IMAGE: nvidia/cuda:11.6.2-devel-ubuntu20.04
    volumes:
    - ./evaluation:/evaluation
    - ./datasets:/datasets
    stop_signal: SIGINT
    command:
    - '8'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 4
            capabilities:
            - gpu
    environment:
    - TZ=America/Detroit
  worker_9:
    build:
      context: .
      dockerfile: ./evaluation/executor/Dockerfile_worker_gpu
      args:
        WORKER_IMAGE: nvidia/cuda:11.6.2-devel-ubuntu20.04
    volumes:
    - ./evaluation:/evaluation
    - ./datasets:/datasets
    stop_signal: SIGINT
    command:
    - '9'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 4
            capabilities:
            - gpu
    environment:
    - TZ=America/Detroit
  worker_10:
    build:
      context: .
      dockerfile: ./evaluation/executor/Dockerfile_worker_gpu
      args:
        WORKER_IMAGE: nvidia/cuda:11.6.2-devel-ubuntu20.04
    volumes:
    - ./evaluation:/evaluation
    - ./datasets:/datasets
    stop_signal: SIGINT
    command:
    - '10'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 4
            capabilities:
            - gpu
    environment:
    - TZ=America/Detroit
  worker_11:
    build:
      context: .
      dockerfile: ./evaluation/executor/Dockerfile_worker_gpu
      args:
        WORKER_IMAGE: nvidia/cuda:11.6.2-devel-ubuntu20.04
    volumes:
    - ./evaluation:/evaluation
    - ./datasets:/datasets
    stop_signal: SIGINT
    command:
    - '11'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 4
            capabilities:
            - gpu
    environment:
    - TZ=America/Detroit
  worker_12:
    build:
      context: .
      dockerfile: ./evaluation/executor/Dockerfile_worker_gpu
      args:
        WORKER_IMAGE: nvidia/cuda:11.6.2-devel-ubuntu20.04
    volumes:
    - ./evaluation:/evaluation
    - ./datasets:/datasets
    stop_signal: SIGINT
    command:
    - '12'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 4
            capabilities:
            - gpu
    environment:
    - TZ=America/Detroit
  worker_13:
    build:
      context: .
      dockerfile: ./evaluation/executor/Dockerfile_worker_gpu
      args:
        WORKER_IMAGE: nvidia/cuda:11.6.2-devel-ubuntu20.04
    volumes:
    - ./evaluation:/evaluation
    - ./datasets:/datasets
    stop_signal: SIGINT
    command:
    - '13'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 4
            capabilities:
            - gpu
    environment:
    - TZ=America/Detroit
  worker_14:
    build:
      context: .
      dockerfile: ./evaluation/executor/Dockerfile_worker_gpu
      args:
        WORKER_IMAGE: nvidia/cuda:11.6.2-devel-ubuntu20.04
    volumes:
    - ./evaluation:/evaluation
    - ./datasets:/datasets
    stop_signal: SIGINT
    command:
    - '14'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 4
            capabilities:
            - gpu
    environment:
    - TZ=America/Detroit
  worker_15:
    build:
      context: .
      dockerfile: ./evaluation/executor/Dockerfile_worker_gpu
      args:
        WORKER_IMAGE: nvidia/cuda:11.6.2-devel-ubuntu20.04
    volumes:
    - ./evaluation:/evaluation
    - ./datasets:/datasets
    stop_signal: SIGINT
    command:
    - '15'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 4
            capabilities:
            - gpu
    environment:
    - TZ=America/Detroit
