version: '3.9'

services:
  scheduler:
    build:
      context: .
      dockerfile: ./propius/scheduler/Dockerfile
    volumes:
    - ./propius/scheduler:/propius/scheduler
    - ./propius/global_config.yml:/propius/global_config.yml
    - ./propius/monitor:/propius/monitor
    depends_on:
    - job_db
    - client_db_0
    - client_db_1
    stop_signal: SIGINT
    environment:
    - TZ=America/Detroit

  job_manager:
    build:
      context: .
      dockerfile: ./propius/job_manager/Dockerfile
    ports:
    - 50001:50001
    volumes:
    - ./propius/job_manager:/propius/job_manager
    - ./propius/global_config.yml:/propius/global_config.yml
    - ./propius/monitor:/propius/monitor
    depends_on:
    - scheduler
    stop_signal: SIGINT
    environment:
    - TZ=America/Detroit

  load_balancer:
    build:
      context: .
      dockerfile: ./propius/load_balancer/Dockerfile
    ports:
    - 50002:50002
    volumes:
    - ./propius/load_balancer:/propius/load_balancer
    - ./propius/global_config.yml:/propius/global_config.yml
    - ./propius/monitor:/propius/monitor
    depends_on:
    - client_manager_0
    stop_signal: SIGINT
    environment:
    - TZ=America/Detroit

  job_db:
    build:
      context: .
      dockerfile: ./propius/database/Dockerfile
    command: ['6379']
    environment:
    - TZ=America/Detroit

  client_manager_0:
    build:
      context: .
      dockerfile: ./propius/client_manager/Dockerfile
    volumes:
    - ./propius/client_manager:/propius/client_manager
    - ./propius/global_config.yml:/propius/global_config.yml
    - ./propius/monitor:/propius/monitor
    depends_on:
    - job_db
    - client_db_0
    command:
    - '0'
    environment:
    - TZ=America/Detroit
