# Global config for simulation

# Scheduling algorithm ['fifo', 'random', 'srtf', 'srdf', 'irs', 'irs2']
sched_alg: 'irs'

# Scheduling option
proactive: True

# Scheduling metadata (optional)
standard_round_time: 3
irs_epsilon: 0

# Scheduler address
sched_ip: localhost
sched_port: 50000

# Client manager address
client_manager_ip: localhost
client_manager_port: 50001

# Client simulation number
client_num: 50000
# Client check in distribution over time
# 0 is uniform distribution, 1 is normal distribution
client_is_uniform: 0

# Job manager address
job_manager_ip: localhost
job_manager_port: 50002

# Job profile number
job_profile_num : 9
# Job total number
total_job : 200
# Job constraint
job_public_constraint:
  - cpu
  - memory
  - os
job_private_constraint: []
  # - datasetsize

# Job driver address
# If job number is 20, there will be 20 job addresses, starting from the defined port number
job_driver_ip: localhost
job_driver_starting_port: 51000

# Total simulation time
total_running_second: 1200

# Redis DB address
db_ip: localhost
db_port: 6379

# Client data expiration time in Redis DB
client_expire_time: 100

# Client default ping expiration time. Client will try to ping job during this time
default_ping_exp_time: 100
# Define the scale of the specifications
metric_scale: 100

# Fedscale simulation
num_executors: 100
num_clients: 100
data_dir: ./benchmark/dataset/data/femnist