# Global config

# ---Addresses---
load_balancer_ip: localhost
load_balancer_port: 50000

client_manager_num: 2
client_manager:
  - 0:
    ip: localhost
    port: 50004
    client_db_port: 6380
  - 1:
    ip: localhost
    port: 50005
    client_db_port: 6381

job_db_ip: localhost
job_db_port: 6379

job_manager_ip: localhost
job_manager_port: 50002

scheduler_ip: localhost
scheduler_port: 50003

# ---Scheduling---
# Scheduling algorithm ['fifo', 'random', 'srtf', 'srdf', 'irs', 'irs2']
sched_alg: 'irs'

max_task_offer_list_len: 10

# Scheduling metadata (optional)
standard_round_time: 30
irs_epsilon: 0

# ---Client---

# ---Constraint/spec setting---
# Job constraint
job_public_constraint:
  - cpu
  - memory
  - os
job_private_constraint: []
  # - datasetsize

# Define the scale of the specifications
metric_scale: 100

# ---Database setting---
# Client data expiration time in Redis DB
client_expire_time: 100

# ---Simulation---
# Client simulation number
client_num: 60000

# Client check in distribution over time
client_is_uniform: False

# Job profile number
job_profile_num : 9
# Job total number
total_job : 200

# If job number is 20, there will be 20 job addresses, starting from the defined port number
job_driver_ip: localhost
job_driver_starting_port: 53000

# Total simulation time
total_running_second: 1200

# Fedscale run
num_executors: 100
num_clients: 100
data_dir: ./benchmark/dataset/data/femnist
