# Server setting
connection_timeout: 800

# Training and testing aggregator setting
demand: 2
total_round: 3
over_selection: 2

# Training and testing client setting
engine: pytorch
model: mobilenet
dataset: femnist
learning_rate: 0.05
num_loaders: 1
local_steps: 10
loss_decay: 0.95
batch_size: 20

gradient_policy: fed-yogi
yogi_eta: 1.e-2
yogi_tau: 1.e-3
yogi_beta1: 0.9
yogi_beta2: 0.99

# Client constraints
public_constraint:
    cpu_f: 3
    ram: 4
    fp16_mem: 600
    android_os: 8
private_constraint:
    dataset_size: 100