# Training and testing aggregator setting
demand: 100
total_round: 500
over_selection: 1.3

# Training and testing client setting
engine: pytorch
model: mobilenet
dataset: femnist
learning_rate: 0.05
num_loaders: 4
local_steps: 10
loss_decay: 0.95
batch_size: 20

gradient_policy: fed-yogi
yogi_eta: 1.e-2
yogi_tau: 1.e-3
yogi_beta1: 0.9
yogi_beta2: 0.99

# Client constraints
public_constraint:
    cpu_f: 2
    ram: 2
    fp16_mem: 400
    android_os: 4
private_constraint:
    dataset_size: 100