# Training and testing aggregator setting
demand: 100
total_round: 10
over_selection: 1.3

# Training and testing client setting
engine: pytorch
model: resnet18
dataset: femnist
learning_rate: 0.05
num_loaders: 4
local_steps: 10
loss_decay: 0.95
batch_size: 20

gradient_policy: fed-avg
# yogi_eta: 1.e-2
# yogi_tau: 1.e-3
# yogi_beta1: 0.9
# yogi_beta2: 0.99

# Client constraints
public_constraint:
    cpu_f: 0
    ram: 0
    fp16_mem: 0
    android_os: 0
private_constraint:
    dataset_size: 0