# Server setting
connection_timeout : 100
ps_ip: localhost
ps_port: 61001

# Training and testing setting
engine: pytorch
model: resnet18
data_set: femnist
gradient_policy: fedavg
demand: 1
decay_round: 3 # learning rate decay after decay round
learning_rate: 0.05
decay_factor: 0.9
min_learning_rate: 0.01
rounds: 3 # Total round
eval_interval: 3

tokenizer: None
test_ratio: 0.5
test_bsz: 10
use_cuda: False

# Client constraints
public_constraint:
  - 28
  - 28
  - 28
private_constraint: []
