# Global config
use_docker: True

# ---Addresses---
load_balancer_ip: localhost
load_balancer_port: 50002

client_manager_id_weight: 100000 # for client id assignment
client_manager:
  - ip: localhost
    port: 50003
    client_db_port: 6380

job_db_ip: localhost
job_db_port: 6379

job_manager_ip: localhost
job_manager_port: 50001

scheduler_ip: localhost
scheduler_port: 50000

# ---Scheduling---
# Scheduling algorithm ['fifo', 'random', 'srtf', 'srdf', 'irs', 'irs2']
sched_alg: 'fifo'
max_task_offer_list_len: 10

# Scheduling context
standard_round_time: 100 # default round time for jobs that doesn't have history round
irs_epsilon: 0

# ---Client---
# Client data expiration time in Redis DB
client_expire_time: 1000

# ---Job---
job_expire_time: 604800 # a week
job_max_silent_time: 3600 # one hour; 
# if job doesn't send request to Propius for more than half an hour,
# the job will be removed, unless the job's demand hasn't been fulfilled

# ---Constraint/spec setting---
job_public_constraint:
  - cpu_f
  - ram
  - fp16_mem
  - android_os
job_private_constraint:
  - dataset_size

public_max:
  cpu_f: 24.8
  ram: 16
  fp16_mem: 2800
  android_os: 15

# ---General---
verbose: True
plot: False