load_balancer_ip: localhost
load_balancer_port: 50000

job_public_constraint:
  - cpu_f
  - ram
  - fp16_mem
  - android_os
job_private_constraint:
  - dataset_size

# ---Simulation---
# Client check in distribution over time
client_is_uniform: True
avg_client_rate: 10

client_comm_path: '/data/device_info/client_device_capacity'
client_spec_path: '/data/device_info/client_spec_speed'
client_size_path: '/data/device_info/client_dataset_size'

# Job profile number
job_profile_num : 5
# Job total number
total_job : 5
# Job generation config
avg_interval: 1800

# If job number is 20, there will be 20 job addresses, starting from the defined port number
job_driver_ip: localhost
job_driver_starting_port: 53000

# Total simulation time
# total_running_second: 1200

# ---Execution---
use_cuda: True

executor_ip: localhost
executor_port: 49999

worker:
  - ip: localhost
    port: 49998
    device: cuda:0
  - ip: localhost
    port: 49997
    device: cuda:0
  - ip: localhost
    port: 49996
    device: cuda:0

num_worker: 1

num_loaders: 5

test_bsz: 20
test_ratio: 1

eval_interval: 10

#FEMNIST
# femnist_data_dir: ./datasets/femnist
# femnist_data_map_file: ./datasets/femnist/client_data_mapping/train.csv
# femnist_test_data_map_file: ./datasets/femnist/client_data_mapping/test.csv
femnist_data_dir: /data/FedScale/benchmark/dataset/data/femnist
femnist_data_map_file: /data/FedScale/benchmark/dataset/data/femnist/client_data_mapping/train.csv
femnist_test_data_map_file: /data/FedScale/benchmark/dataset/data/femnist/client_data_mapping/test.csv