# ---Propius setting---
load_balancer_ip: localhost
load_balancer_port: 50002

job_manager_ip: localhost
job_manager_port: 50001

job_public_constraint:
- cpu_f
- ram
- fp16_mem
- android_os
job_private_constraint:
- dataset_size

sched_alg: irs3

# ---Evaluation setting---
speedup_factor: 2.5
test_bsz: 128
test_ratio: 1
eval_interval: 5

# Client number
client_num: 50
client_test_num: 356
ideal_client: true

# Job
total_job: 5
# profile_folder: ./evaluation/job/profile/
profile_folder: ./evaluation/job/profile_policy_test
# profile_folder: ./evaluation/job/dry_profile/   # no training
# profile_folder: './evaluation/job/test_profile/'
job_trace: ./evaluation/job/profile_policy_test/job_trace.txt

# If job number is 20, there will be 20 job addresses, starting from the defined port number
job_driver_ip: localhost
job_driver_starting_port: 60000

# ---Data path---
client_avail_path: ./datasets/device_info/client_behave_trace
client_comm_path: ./datasets/device_info/client_device_capacity
client_spec_path: ./datasets/device_info/client_spec_speed
client_size_path: ./datasets/device_info/client_dataset_size

data_dir: ./datasets/femnist
data_map_file: ./datasets/femnist/client_data_mapping/train.csv
test_data_map_file: ./datasets/femnist/client_data_mapping/test.csv

do_compute: false
is_FA: false

use_cuda: false
use_docker: false

executor_ip: localhost
executor_port: 49999
cuda_device: cuda:0 # if use cuda, else cpu
round_timeout: 3600

# ---Multi worker
worker:
- ip: localhost
  port: 49998
  device: 0
- ip: localhost
  port: 49997
  device: 0
- ip: localhost
  port: 49996
  device: 0
- ip: localhost
  port: 49995
  device: 0
- ip: localhost
  port: 49994
  device: 1
- ip: localhost
  port: 49993
  device: 1
- ip: localhost
  port: 49992
  device: 1
- ip: localhost
  port: 49991
  device: 1
