load_balancer_ip: localhost
load_balancer_port: 50000

job_public_constraint:
  - cpu
  - memory
  - os
job_private_constraint: []
  # - datasetsize


# ---Simulation---
# Client simulation number
client_num: 1000

# Client check in distribution over time
client_is_uniform: False

# Job profile number
job_profile_num : 9
# Job total number
total_job : 25

# If job number is 20, there will be 20 job addresses, starting from the defined port number
job_driver_ip: localhost
job_driver_starting_port: 53000

# Total simulation time
total_running_second: 1200


# ---Execution---
use_cuda: False

executor_ip: localhost
executor_port: 49999

num_worker: 1

num_loaders: 5

test_bsz: 20
test_ratio: 1

#FEMNIST
femnist_data_dir: ./evaluation/datasets/femnist
femnist_data_map_file: ./evaluation/datasets/femnist/client_data_mapping/train.csv
femnist_test_data_map_file: ./evaluation/datasets/femnist/client_data_mapping/test.csv