# ---Propius setting---
load_balancer_ip: localhost
load_balancer_port: 50002

job_manager_ip: localhost
job_manager_port: 50001

job_public_constraint:
- cpu_f
- ram
- fp16_mem
- android_os
job_private_constraint:
- dataset_size

sched_alg: fifo

# ---Evaluation setting---
speedup_factor: 3
test_bsz: 128
test_ratio: 1
eval_interval: 5

# Client number
client_num: 1000
client_test_num: 356
ideal_client: true

# Job
total_job: 1
# profile_folder: ./evaluation/job/profile/
profile_folder: ./evaluation/job/profile_motivation
# profile_folder: ./evaluation/job/dry_profile/   # no training
# profile_folder: './evaluation/job/test_profile/'
job_trace: ./evaluation/job/profile_motivation/job_trace.txt

# If job number is 20, there will be 20 job addresses, starting from the defined port number
job_driver_ip: localhost
job_driver_starting_port: 60000

# ---Data path---
client_avail_path: ./datasets/device_info/client_behave_trace
client_comm_path: ./datasets/device_info/client_device_capacity
client_spec_path: ./datasets/device_info/client_spec_speed
client_size_path: ./datasets/device_info/client_dataset_size

#FEMNIST
femnist_data_dir: ./datasets/femnist
femnist_data_map_file: ./datasets/femnist/client_data_mapping/train.csv
femnist_test_data_map_file: ./datasets/femnist/client_data_mapping/test.csv

# ---Execution framework setting---
do_compute: true
is_FA: false

use_cuda: true
use_docker: true

executor_ip: localhost
executor_port: 49999
cuda_device: cuda:0 # if use cuda, else cpu
round_timeout: 3600

# ---Multi worker
worker:
- ip: localhost
  port: 49998
  device: 2
- ip: localhost
  port: 49997
  device: 2
- ip: localhost
  port: 49996
  device: 2
- ip: localhost
  port: 49995
  device: 2
