load_balancer_ip: localhost
load_balancer_port: 50000

job_public_constraint:
  - cpu
  - memory
  - os
job_private_constraint: []
  # - datasetsize


# ---Simulation---
# Client simulation number
client_num: 10000

# Client check in distribution over time
client_is_uniform: False

client_speed_path: './datasets/device_info/client_device_capacity'

# Job profile number
job_profile_num : 9
# Job total number
total_job : 25

# If job number is 20, there will be 20 job addresses, starting from the defined port number
job_driver_ip: localhost
job_driver_starting_port: 53000

# Total simulation time
total_running_second: 1200


# ---Execution---
use_cuda: False
cuda_device:
  - cuda:0
  - cuda:1

executor_ip: localhost
executor_port: 49999

num_worker: 1

num_loaders: 5

test_bsz: 20
test_ratio: 1

eval_interval: 10

#FEMNIST
femnist_data_dir: ./datasets/femnist
femnist_data_map_file: ./datasets/femnist/client_data_mapping/train.csv
femnist_test_data_map_file: ./datasets/femnist/client_data_mapping/test.csv
# femnist_data_dir: /data/FedScale/benchmark/dataset/data/femnist
# femnist_data_map_file: /data/FedScale/benchmark/dataset/data/femnist/client_data_mapping/train.csv
# femnist_test_data_map_file: /data/FedScale/benchmark/dataset/data/femnist/client_data_mapping/test.csv