# speedup_factor: 5
speedup_factor: 2
load_balancer_ip: localhost
load_balancer_port: 50002

job_manager_ip: localhost
job_manager_port: 50001

sched_alg: fifo

job_public_constraint:
  - cpu_f
  - ram
  - fp16_mem
  - android_os
job_private_constraint:
  - dataset_size

sched_timeout: 360
exec_timeout: 240

# ---Simulation---

client_num: 25000
# client_num: 15000
client_test_num: 50
client_avail_path: './datasets/device_info/client_behave_trace'
client_comm_path: './datasets/device_info/client_device_capacity'
client_spec_path: './datasets/device_info/client_spec_speed'
client_size_path: './datasets/device_info/client_dataset_size'

# profile_folder: './evaluation/job/dry_profile/'
# profile_folder: './evaluation/job/profile/'
profile_folder: './evaluation/job/test_profile/'

# Job profile number

# job_profile_num: 10
job_profile_num: 5

# Job total number
# total_job: 10
total_job: 5
# Job generation config
avg_interval: 1800

# If job number is 20, there will be 20 job addresses, starting from the defined port number
job_driver_ip: localhost
job_driver_starting_port: 60000

# ---Execution---
do_compute: True
use_cuda: True
use_docker: True

executor_ip: localhost
executor_port: 49999
cuda_device: cuda:0 # if use cuda, else cpu
round_timeout: 3600

# ---Multi worker
worker:
  - ip: localhost
    port: 49998
    device: cuda:0
  - ip: localhost
    port: 49997
    device: cuda:0
  - ip: localhost
    port: 49996
    device: cuda:1
  - ip: localhost
    port: 49995
    device: cuda:1

# ---Testing---
test_bsz: 20
test_ratio: 1
eval_interval: 10

#FEMNIST
femnist_data_dir: ./datasets/femnist
femnist_data_map_file: ./datasets/femnist/client_data_mapping/train.csv
femnist_test_data_map_file: ./datasets/femnist/client_data_mapping/test.csv
