load_balancer_ip: localhost
load_balancer_port: 50000

job_public_constraint:
  - cpu
  - memory
  - os
job_private_constraint: []
  # - datasetsize


# ---Simulation---
# Client simulation number
client_num: 60000

# Client check in distribution over time
client_is_uniform: False

# Job profile number
job_profile_num : 9
# Job total number
total_job : 200

# If job number is 20, there will be 20 job addresses, starting from the defined port number
job_driver_ip: localhost
job_driver_starting_port: 53000

# Total simulation time
total_running_second: 1200