# Dataset and model
model: resnet18
data_set: femnist
num_loaders: 8
memory_capacity: 1

# Training setup
tokenizer:
local_steps: 10
batch_size: 10
gradient_policy: SGD
learning_rate: 0.05
use_cuda: False
batch_size: 10
loss_decay: 0.95
# Test setup
test_ratio: 0.5
test_bsz: 10

public_spec:
  - 70
  - 70
  - 70
private_spec: []
