version: "3.9"

services:
  client_db_0:
    image: redis/redis-stack-server:latest
    ports:
      - "6380:6379"
    volumes:
        - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6380", "ping"]
      interval: 2s
      timeout: 1m30s
      retries: 5
      start_period: 5s

volumes:
  redis_data: