# Server setting
connection_timeout: 500

job_manager_ip: localhost
job_manager_port: 50002

# Training and testing aggregator setting
demand: 10
total_round: 10  # Total round
over_selection: 1.3

# Training and testing client setting
engine: pytorch
model: mobilenet
dataset: femnist
learning_rate: 0.05
num_loaders: 6
local_steps: 10
loss_decay: 0.95
batch_size: 10

# Client constraints
public_constraint:
    cpu_f: 0
    ram: 0
    fp16_mem: 0
    android_os: 0
private_constraint:
    dataset_size: 100
