# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parameter_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='parameter_server.proto',
  package='parameter_server',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16parameter_server.proto\x12\x10parameter_server\"%\n\x04plan\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x08\x12\x10\n\x08workload\x18\x02 \x01(\x05\"\x17\n\tclient_id\x12\n\n\x02id\x18\x01 \x01(\x05\"2\n\rclient_report\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x0e\n\x06result\x18\x02 \x01(\x02\"\x07\n\x05\x65mpty2\xa8\x01\n\x10Parameter_server\x12G\n\x0e\x43LIENT_REQUEST\x12\x1b.parameter_server.client_id\x1a\x16.parameter_server.plan\"\x00\x12K\n\rCLIENT_REPORT\x12\x1f.parameter_server.client_report\x1a\x17.parameter_server.empty\"\x00\x62\x06proto3'
)




_PLAN = _descriptor.Descriptor(
  name='plan',
  full_name='parameter_server.plan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ack', full_name='parameter_server.plan.ack', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='workload', full_name='parameter_server.plan.workload', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=81,
)


_CLIENT_ID = _descriptor.Descriptor(
  name='client_id',
  full_name='parameter_server.client_id',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='parameter_server.client_id.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=106,
)


_CLIENT_REPORT = _descriptor.Descriptor(
  name='client_report',
  full_name='parameter_server.client_report',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='parameter_server.client_report.client_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='parameter_server.client_report.result', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=158,
)


_EMPTY = _descriptor.Descriptor(
  name='empty',
  full_name='parameter_server.empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=167,
)

DESCRIPTOR.message_types_by_name['plan'] = _PLAN
DESCRIPTOR.message_types_by_name['client_id'] = _CLIENT_ID
DESCRIPTOR.message_types_by_name['client_report'] = _CLIENT_REPORT
DESCRIPTOR.message_types_by_name['empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

plan = _reflection.GeneratedProtocolMessageType('plan', (_message.Message,), {
  'DESCRIPTOR' : _PLAN,
  '__module__' : 'parameter_server_pb2'
  # @@protoc_insertion_point(class_scope:parameter_server.plan)
  })
_sym_db.RegisterMessage(plan)

client_id = _reflection.GeneratedProtocolMessageType('client_id', (_message.Message,), {
  'DESCRIPTOR' : _CLIENT_ID,
  '__module__' : 'parameter_server_pb2'
  # @@protoc_insertion_point(class_scope:parameter_server.client_id)
  })
_sym_db.RegisterMessage(client_id)

client_report = _reflection.GeneratedProtocolMessageType('client_report', (_message.Message,), {
  'DESCRIPTOR' : _CLIENT_REPORT,
  '__module__' : 'parameter_server_pb2'
  # @@protoc_insertion_point(class_scope:parameter_server.client_report)
  })
_sym_db.RegisterMessage(client_report)

empty = _reflection.GeneratedProtocolMessageType('empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'parameter_server_pb2'
  # @@protoc_insertion_point(class_scope:parameter_server.empty)
  })
_sym_db.RegisterMessage(empty)



_PARAMETER_SERVER = _descriptor.ServiceDescriptor(
  name='Parameter_server',
  full_name='parameter_server.Parameter_server',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=170,
  serialized_end=338,
  methods=[
  _descriptor.MethodDescriptor(
    name='CLIENT_REQUEST',
    full_name='parameter_server.Parameter_server.CLIENT_REQUEST',
    index=0,
    containing_service=None,
    input_type=_CLIENT_ID,
    output_type=_PLAN,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CLIENT_REPORT',
    full_name='parameter_server.Parameter_server.CLIENT_REPORT',
    index=1,
    containing_service=None,
    input_type=_CLIENT_REPORT,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PARAMETER_SERVER)

DESCRIPTOR.services_by_name['Parameter_server'] = _PARAMETER_SERVER

# @@protoc_insertion_point(module_scope)
